name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme myst-parser
        pip install -e .
        
    - name: Build documentation
      run: |
        mkdir -p docs
        sphinx-quickstart docs --sep --project "Signal Messenger Python API" --author "Your Name" --no-makefile --no-batchfile -q
        sphinx-apidoc -o docs/source signal_messenger
        cd docs && make html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html